#include "MAIN.h"
#include <iostream>
#include <fstream>
#include <string>
using namespace std;
void mainplayermenu()//Not in use
{
	Menu::Title("");
	Menu::Subtitle("Character Appearance");
	Menu::MenuOption("Clothing Options", clothingmenu);
	//Menu::MenuOption("Plastic Surgery Options", plasticmenu); Online Only
	//Menu::MenuOption("Hair And Makeup Options", Makeupmenu);Online Only


}

bool SetModel(char* option, Hash Model)
{
	Option(option);
	if (Menu::Settings::currentOption == Menu::Settings::optionCount)
	{
		if (Menu::Settings::selectPressed)
		{
			if (STREAMING::IS_MODEL_IN_CDIMAGE(Model))
			{
				if (STREAMING::IS_MODEL_VALID(Model))
				{
					STREAMING::REQUEST_MODEL(Model);
					if (STREAMING::HAS_MODEL_LOADED(Model))
					{
						PLAYER::SET_PLAYER_MODEL(PLAYER::PLAYER_ID(), Model);
						STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(Model);
						return true;
					}
					else return false;
				}
			}
			return true;
		}
	}
	return false;
}
bool SetModel(char* Model, char* option)
{
	Option(option);
	if (Menu::Settings::currentOption == Menu::Settings::optionCount)
	{
		if (Menu::Settings::selectPressed)
		{
			if (STREAMING::IS_MODEL_IN_CDIMAGE(key(Model)))
			{
				if (STREAMING::IS_MODEL_VALID(key(Model)))
				{
					STREAMING::REQUEST_MODEL(key(Model));
					if (STREAMING::HAS_MODEL_LOADED(key(Model)))
					{
						PLAYER::SET_PLAYER_MODEL(PLAYER::PLAYER_ID(), key(Model));
						STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(key(Model));
						return true;
					}
					else return false;
				}
			}
			return true;
		}
	}
	return false;
}

void ModelMenu()
{
	Menu::Title("");
	Menu::Subtitle("Player Models");
	Menu::MenuOption("Animal Models", AModel);
	Menu::MenuOption("Ambient Female Models", AmbientFemale_);
	Menu::MenuOption("Ambient Male Models", AmbientMale_);
	Menu::MenuOption("Cutscene Models", Cutscene_);
	Menu::MenuOption("Gang Female Models", GangFemale_);
	Menu::MenuOption("Gang Male Models", GangMale_);
	Menu::MenuOption("Story Models", Story_);
	Menu::MenuOption("Multiplayer Models", Multiplayer_);
	Menu::MenuOption("Scenario Female Models", ScenarioFemale_);
	Menu::MenuOption("Scenario Male Models", ScenarioMale_);
	Menu::MenuOption("Story Scenario Female Models", StoryScenarioFemale_);
	Menu::MenuOption("Story Scenario Male Models", StoryScenarioMale_);
	Menu::MenuOption("Other Models", other_);


}
//thanks fr0hawk boooo for doing models
void AnimalModels()//Done
{
	Menu::Title("");
	Menu::Subtitle("Player Models");
	SetModel("Cat", 1462895032);
	SetModel("Boar", -832573324);
	SetModel("Cormorant", 1457690978);
	SetModel("Cow", -50684386);
	SetModel("Coyote", 1682622302);
	SetModel("Crow", 402729631);
	SetModel("Deer", -664053099);
	SetModel("Fish", 802685111);
	SetModel("Dolphin", -1950698411);
	SetModel("HammerShark", 1015224100);
	SetModel("Hen", 1794449327);
	SetModel("Humpback", 1193010354);
	SetModel("Husky", 1318032802);
	SetModel("KillerWhale", -1920284487);
	SetModel("MountainLion", 307287994);
	SetModel("Pig", -1323586730);
	SetModel("Pigeon", 111281960);
	SetModel("Poodle", 1125994524);
	SetModel("Pug", 1832265812);
	SetModel("Rabbit", -541762431);
	SetModel("Rat", -1011537562);
	SetModel("Retriever", 882848737);
	SetModel("Rhesus", -1026527405);
	SetModel("Rottweiler", -1788665315);
	SetModel("Seagull", -745300483);
	SetModel("Shepherd", 1126154828);
	SetModel("Stingray", -1589092019);
	SetModel("TigerShark", 113504370);
	SetModel("Westy", -1384627013);
	
}
void AmbientFemale()
{
	Menu::Title("");
	Menu::Subtitle("Player Models");
	SetModel("a_f_m_beach_01", "Beach Female");
	SetModel("a_f_m_trampbeac_01", "Beach Tramp Female");
	SetModel("a_f_y_beach_01", "Beach Young Female");
	SetModel("a_f_m_bevhills_01", "Beverly Hills Female");
	SetModel("a_f_m_bevhills_02", "Beverly Hills Female 2");
	SetModel("a_f_y_bevhills_01", "Beverly Hills Young Female");
	SetModel("a_f_y_bevhills_02", "Beverly Hills Young Female 2");
	SetModel("a_f_y_bevhills_03", "Beverly Hills Young Female 3");
	SetModel("a_f_y_bevhills_04", "Beverly Hills Young Female 4");
	SetModel("a_f_m_bodybuild_01", "Bodybuilder Female");
	SetModel("a_f_m_business_02", "Business Female 2");
	SetModel("a_f_y_business_01", "Business Young Female");
	SetModel("a_f_y_business_02", "Business Young Female 2");
	SetModel("a_f_y_business_03", "Business Young Female 3");
	SetModel("a_f_y_business_04", "Business Young Female 4");
	SetModel("a_f_m_downtown_01", "Downtown Female");
	SetModel("a_f_y_scdressy_01", "Dressy Female");
	SetModel("a_f_m_eastsa_01", "East SA Female");
	SetModel("a_f_m_eastsa_02", "East SA Female 2");
	SetModel("a_f_y_eastsa_01", "East SA Young Female");
	SetModel("a_f_y_eastsa_02", "East SA Young Female 2");
	SetModel("a_f_y_eastsa_03", "East SA Young Female 3");
	SetModel("a_f_y_epsilon_01", "Epsilon Female");
	SetModel("a_f_m_fatbla_01", "Fat Black Female");
	SetModel("a_f_m_fatcult_01", "Fat Cult Female");
	SetModel("a_f_m_fatwhite_01", "Fat White Female");
	SetModel("a_f_y_femaleagent", "Female Agent");
	SetModel("a_f_y_fitness_01", "Fitness Female");
	SetModel("a_f_y_fitness_02", "Fitness Female 2");
	SetModel("a_f_y_genhot_01", "General Hot Young Female");
	SetModel("a_f_o_genstreet_01", "General Street Old Female");
	SetModel("a_f_y_gencaspat_01", "Casual Casino Guest");
	SetModel("a_f_y_smartcaspat_01", "Formel Casino Guest");
	SetModel("a_f_y_golfer_01", "Golfer Young Female");
	SetModel("a_f_y_hiker_01", "Hiker Female");
	SetModel("a_f_y_hippie_01", "Hippie Female");
	SetModel("a_f_y_hipster_01", "Hipster Female");
	SetModel("a_f_y_hipster_02", "Hipster Female 2");
	SetModel("a_f_y_hipster_03", "Hipster Female 3");
	SetModel("a_f_y_hipster_04", "Hipster Female 4");
	SetModel("a_f_o_indian_01", "Indian Old Female");
	SetModel("a_f_y_indian_01", "Indian Young Female");
	SetModel("a_f_y_runner_01", "Jogger Female");
	SetModel("a_f_y_juggalo_01", "Juggalo Female");
	SetModel("a_f_m_ktown_01", "Korean Female");
	SetModel("a_f_m_ktown_02", "Korean Female 2");
	SetModel("a_f_o_ktown_01", "Korean Old Female");
	SetModel("a_f_m_prolhost_01", "Prologue Host Female");
	SetModel("a_f_y_rurmeth_01", "Rural Meth Addict Female");
	SetModel("a_f_m_salton_01", "Salton Female");
	SetModel("a_f_o_salton_01", "Salton Old Female");
	SetModel("a_f_y_skater_01", "Skater Female");
	SetModel("a_f_m_skidrow_01", "Skid Row Female");
	SetModel("a_f_m_soucent_01", "South Central Female");
	SetModel("a_f_m_soucent_02", "South Central Female 2");
	SetModel("a_f_m_soucentmc_01", "South Central MC Female");
	SetModel("a_f_o_soucent_01", "South Central Old Female");
	SetModel("a_f_o_soucent_02", "South Central Old Female 2");
	SetModel("a_f_y_soucent_01", "South Central Young Female");
	SetModel("a_f_y_soucent_02", "South Central Young Female 2");
	SetModel("a_f_y_soucent_03", "South Central Young Female 3");
	SetModel("a_f_y_tennis_01", "Tennis Player Female");
	SetModel("a_f_y_topless_01", "Topless");
	SetModel("a_f_m_tourist_01", "Tourist Female");
	SetModel("a_f_y_tourist_01", "Tourist Young Female");
	SetModel("a_f_y_tourist_02", "Tourist Young Female 2");
	SetModel("a_f_m_tramp_01", "Tramp Female");
	SetModel("a_f_y_vinewood_01", "Vinewood Female");
	SetModel("a_f_y_vinewood_02", "Vinewood Female 2");
	SetModel("a_f_y_vinewood_03", "Vinewood Female 3");
	SetModel("a_f_y_vinewood_04", "Vinewood Female 4");
	SetModel("a_f_y_yoga_01", "Yoga Female");
	SetModel("a_f_y_clubcust_01", "Club Customer Female 1");
	SetModel("a_f_y_clubcust_02", "Club Customer Female 2");
	SetModel("a_f_y_clubcust_03", "Club Customer Female 3");
}
void AmbientMale()
{
	Menu::Title("");
	Menu::Subtitle("Player Models");
	SetModel("a_m_m_afriamer_01", "African American Male");
	SetModel("a_m_m_acult_01", "Altruist Cult Mid-Age Male");
	SetModel("a_m_o_acult_01", "Altruist Cult Old Male");
	SetModel("a_m_o_acult_02", "Altruist Cult Old Male 2");
	SetModel("a_m_y_acult_01", "Altruist Cult Young Male");
	SetModel("a_m_y_acult_02", "Altruist Cult Young Male 2");
	SetModel("a_m_m_beach_01", "Beach Male");
	SetModel("a_m_m_beach_02", "Beach Male 2");
	SetModel("a_m_y_musclbeac_01", "Beach Muscle Male");
	SetModel("a_m_y_musclbeac_02", "Beach Muscle Male 2");
	SetModel("a_m_m_mlcrisis_01", "Midlife Crisis Casino Bikers");
	SetModel("a_m_y_gencaspat_01", "Casual Casino Guests");
	SetModel("a_m_y_smartcaspat_01", "Formel Casino Guests");
	SetModel("a_m_o_beach_01", "Beach Old Male");
	SetModel("a_m_m_trampbeac_01", "Beach Tramp Male");
	SetModel("a_m_y_beach_01", "Beach Young Male");
	SetModel("a_m_y_beach_02", "Beach Young Male 2");
	SetModel("a_m_y_beach_03", "Beach Young Male 3");
	SetModel("a_m_m_bevhills_01", "Beverly Hills Male");
	SetModel("a_m_m_bevhills_02", "Beverly Hills Male 2");
	SetModel("a_m_y_bevhills_01", "Beverly Hills Young Male");
	SetModel("a_m_y_bevhills_02", "Beverly Hills Young Male 2");
	SetModel("a_m_y_stbla_01", "Black Street Male");
	SetModel("a_m_y_stbla_02", "Black Street Male 2");
	SetModel("a_m_y_breakdance_01", "Breakdancer Male");
	SetModel("a_m_y_busicas_01", "Business Casual");
	SetModel("a_m_m_business_01", "Business Male");
	SetModel("a_m_y_business_01", "Business Young Male");
	SetModel("a_m_y_business_02", "Business Young Male 2");
	SetModel("a_m_y_business_03", "Business Young Male 3");
	SetModel("a_m_y_cyclist_01", "Cyclist Male");
	SetModel("a_m_y_dhill_01", "Downhill Cyclist");
	SetModel("a_m_y_downtown_01", "Downtown Male");
	SetModel("a_m_m_eastsa_01", "East SA Male");
	SetModel("a_m_m_eastsa_02", "East SA Male 2");
	SetModel("a_m_y_eastsa_01", "East SA Young Male");
	SetModel("a_m_y_eastsa_02", "East SA Young Male 2");
	SetModel("a_m_y_epsilon_01", "Epsilon Male");
	SetModel("a_m_y_epsilon_02", "Epsilon Male 2");
	SetModel("a_m_m_farmer_01", "Farmer");
	SetModel("a_m_m_fatlatin_01", "Fat Latino Male");
	SetModel("a_m_y_gay_01", "Gay Male");
	SetModel("a_m_y_gay_02", "Gay Male 2");
	SetModel("a_m_m_genfat_01", "General Fat Male");
	SetModel("a_m_m_genfat_02", "General Fat Male 2");
	SetModel("a_m_o_genstreet_01", "General Street Old Male");
	SetModel("a_m_y_genstreet_01", "General Street Young Male");
	SetModel("a_m_y_genstreet_02", "General Street Young Male 2");
	SetModel("a_m_m_golfer_01", "Golfer Male");
	SetModel("a_m_y_golfer_01", "Golfer Young Male");
	SetModel("a_m_m_hasjew_01", "Hasidic Jew Male");
	SetModel("a_m_y_hasjew_01", "Hasidic Jew Young Male");
	SetModel("a_m_y_hiker_01", "Hiker Male");
	SetModel("a_m_m_hillbilly_01", "Hillbilly Male");
	SetModel("a_m_m_hillbilly_02", "Hillbilly Male 2");
	SetModel("a_m_y_hippy_01", "Hippie Male");
	SetModel("a_m_y_hipster_01", "Hipster Male");
	SetModel("a_m_y_hipster_02", "Hipster Male 2");
	SetModel("a_m_y_hipster_03", "Hipster Male 3");
	SetModel("a_m_m_indian_01", "Indian Male");
	SetModel("a_m_y_indian_01", "Indian Young Male");
	SetModel("a_m_y_jetski_01", "Jetskier");
	SetModel("a_m_y_runner_01", "Jogger Male");
	SetModel("a_m_y_runner_02", "Jogger Male 2");
	SetModel("a_m_y_juggalo_01", "Juggalo Male");
	SetModel("a_m_m_ktown_01", "Korean Male");
	SetModel("a_m_o_ktown_01", "Korean Old Male");
	SetModel("a_m_y_ktown_01", "Korean Young Male");
	SetModel("a_m_y_ktown_02", "Korean Young Male 2");
	SetModel("a_m_m_stlat_02", "Latino Street Male 2");
	SetModel("a_m_y_stlat_01", "Latino Street Young Male");
	SetModel("a_m_y_latino_01", "Latino Young Male");
	SetModel("a_m_m_malibu_01", "Malibu Male");
	SetModel("a_m_y_methhead_01", "Meth Addict");
	SetModel("a_m_m_mexlabor_01", "Mexican Labourer");
	SetModel("a_m_m_mexcntry_01", "Mexican Rural");
	SetModel("a_m_y_mexthug_01", "Mexican Thug");
	SetModel("a_m_y_motox_01", "Motocross Biker");
	SetModel("a_m_y_motox_02", "Motocross Biker 2");
	SetModel("a_m_m_og_boss_01", "OG Boss");
	SetModel("a_m_m_paparazzi_01", "Paparazzi Male");
	SetModel("a_m_m_polynesian_01", "Polynesian");
	SetModel("a_m_y_polynesian_01", "Polynesian Young");
	SetModel("a_m_m_prolhost_01", "Prologue Host Male");
	SetModel("a_m_y_roadcyc_01", "Road Cyclist");
	SetModel("a_m_m_rurmeth_01", "Rural Meth Addict Male");
	SetModel("a_m_m_salton_01", "Salton Male");
	SetModel("a_m_m_salton_02", "Salton Male 2");
	SetModel("a_m_m_salton_03", "Salton Male 3");
	SetModel("a_m_m_salton_04", "Salton Male 4");
	SetModel("a_m_o_salton_01", "Salton Old Male");
	SetModel("a_m_y_salton_01", "Salton Young Male");
	SetModel("a_m_m_skater_01", "Skater Male");
	SetModel("a_m_y_skater_01", "Skater Young Male");
	SetModel("a_m_y_skater_02", "Skater Young Male 2");
	SetModel("a_m_m_skidrow_01", "Skid Row Male");
	SetModel("a_m_m_socenlat_01", "South Central Latino Male");
	SetModel("a_m_m_soucent_01", "South Central Male");
	SetModel("a_m_m_soucent_02", "South Central Male 2");
	SetModel("a_m_m_soucent_03", "South Central Male 3");
	SetModel("a_m_m_soucent_04", "South Central Male 4");
	SetModel("a_m_o_soucent_01", "South Central Old Male");
	SetModel("a_m_o_soucent_02", "South Central Old Male 2");
	SetModel("a_m_o_soucent_03", "South Central Old Male 3");
	SetModel("a_m_y_soucent_01", "South Central Young Male");
	SetModel("a_m_y_soucent_02", "South Central Young Male 2");
	SetModel("a_m_y_soucent_03", "South Central Young Male 3");
	SetModel("a_m_y_soucent_04", "South Central Young Male 4");
	SetModel("a_m_y_sunbathe_01", "Sunbather Male");
	SetModel("a_m_y_surfer_01", "Surfer");
	SetModel("a_m_m_tennis_01", "Tennis Player Male");
	SetModel("a_m_m_tourist_01", "Tourist Male");
	SetModel("a_m_m_tramp_01", "Tramp Male");
	SetModel("a_m_o_tramp_01", "Tramp Old Male");
	SetModel("a_m_m_tranvest_01", "Transvestite Male");
	SetModel("a_m_m_tranvest_02", "Transvestite Male 2");
	SetModel("a_m_y_beachvesp_01", "Vespucci Beach Male");
	SetModel("a_m_y_beachvesp_02", "Vespucci Beach Male 2");
	SetModel("a_m_y_vindouche_01", "Vinewood Douche");
	SetModel("a_m_y_vinewood_01", "Vinewood Male");
	SetModel("a_m_y_vinewood_02", "Vinewood Male 2");
	SetModel("a_m_y_vinewood_03", "Vinewood Male 3");
	SetModel("a_m_y_vinewood_04", "Vinewood Male 4");
	SetModel("a_m_y_stwhi_01", "White Street Male");
	SetModel("a_m_y_stwhi_02", "White Street Male 2");
	SetModel("a_m_y_yoga_01", "Yoga Male");
	SetModel("a_m_y_clubcust_01", "Club Customer Male 1");
	SetModel("a_m_y_clubcust_02", "Club Customer Male 2");
	SetModel("a_m_y_clubcust_03", "Club Customer Male 3");

}
void Cutscene()
{
	Menu::Title("");
	Menu::Subtitle("Player Models");
	SetModel("csb_abigail", "Abigail Mathers");
	SetModel("csb_agent", "Agent");
	SetModel("csb_agatha", "Agatha Baker");
	SetModel("csb_avery", "Avery Duggan");
	SetModel("csb_mp_agent14", "Agent 14");
	SetModel("cs_amandatownley", "Amanda De Santa");
	SetModel("cs_andreas", "Andreas Sanchez");
	SetModel("csb_anita", "Anita Mendoza");
	SetModel("csb_anton", "Anton Beaudelaire");
	SetModel("cs_ashley", "Ashley Butler");
	SetModel("csb_avon", "Avon Hertz");
	SetModel("csb_ballasog", "Ballas OG");
	SetModel("cs_bankman", "Bank Manager");
	SetModel("cs_barry", "Barry");
	SetModel("cs_beverly", "Beverly Felton");
	SetModel("csb_brucie2", "Brucie Kibbutz");
	SetModel("cs_orleans", "Bigfoot");
	SetModel("csb_bogdan", "Bogdan");
	SetModel("cs_brad", "Brad");
	SetModel("cs_bradcadaver", "Brad's Cadaver");
	SetModel("csb_bride", "Bride");
	SetModel("csb_burgerdrug", "Burger Drug Worker");
	SetModel("csb_car3guy1", "Car 3 Guy 1");
	SetModel("csb_car3guy2", "Car 3 Guy 2");
	SetModel("cs_carbuyer", "Car Buyer");
	SetModel("cs_casey", "Casey");
	SetModel("csb_chef", "Chef");
	SetModel("csb_chef2", "Chef");
	SetModel("csb_chin_goon", "Chinese Goon");
	SetModel("cs_clay", "Clay Simons (The Lost)");
	SetModel("csb_cletus", "Cletus");
	SetModel("csb_cop", "Cop");
	SetModel("cs_chrisformage", "Cris Formage");
	SetModel("csb_customer", "Customer");
	SetModel("cs_dale", "Dale");
	SetModel("cs_davenorton", "Dave Norton");
	SetModel("cs_debra", "Debra");
	SetModel("cs_denise", "Denise");
	SetModel("csb_denise_friend", "Denise's Friend");
	SetModel("cs_devin", "Devin");
	SetModel("csb_popov", "Dima Popov");
	SetModel("cs_dom", "Dom Beasley");
	SetModel("cs_drfriedlander", "Dr. Friedlander");
	SetModel("cs_tomepsilon", "Epsilon Tom");
	SetModel("cs_fabien", "Fabien");
	SetModel("csb_ramp_gang", "Families Gang Member?");
	SetModel("cs_mrk", "Ferdinand Kerimov (Mr. K)");
	SetModel("cs_fbisuit_01", "FIB Suit");
	SetModel("cs_floyd", "Floyd Hebert");
	SetModel("csb_fos_rep", "FOS Rep?");
	SetModel("csb_g", "Gerald");
	SetModel("csb_groom", "Groom");
	SetModel("csb_grove_str_dlr", "Grove Street Dealer");
	SetModel("cs_guadalope", "Guadalope");
	SetModel("cs_gurk", "GURK?");
	SetModel("csb_hao", "Hao");
	SetModel("csb_ramp_hic", "Hick");
	SetModel("csb_ramp_hipster", "Hipster");
	SetModel("csb_hugh", "Hugh Welsh");
	SetModel("cs_hunter", "Hunter");
	SetModel("csb_imran", "Imran Shinowa");
	SetModel("csb_jackhowitzer", "Jack Howitzer");
	SetModel("cs_janet", "Janet");
	SetModel("csb_janitor", "Janitor");
	SetModel("cs_jewelass", "Jeweller Assistant");
	SetModel("cs_jimmyboston", "Jimmy Boston");
	SetModel("cs_jimmydisanto", "Jimmy De Santa");
	SetModel("cs_johnnyklebitz", "Johnny Klebitz");
	SetModel("cs_josef", "Josef");
	SetModel("cs_josh", "Josh");
	SetModel("cs_karen_daniels", "Karen Daniels");
	SetModel("cs_lamardavis", "Lamar Davis");
	SetModel("cs_lazlow", "Lazlow");
	SetModel("cs_lestercrest", "Lester Crest");
	SetModel("cs_lifeinvad_01", "Life Invader");
	SetModel("cs_magenta", "Magenta");
	SetModel("cs_manuel", "Manuel");
	SetModel("csb_ramp_marine", "Marine");
	SetModel("cs_marnie", "Marnie Allen");
	SetModel("cs_martinmadrazo", "Martin Madrazo");
	SetModel("cs_maryann", "Mary-Ann Quinn");
	SetModel("csb_maude", "Maude");
	SetModel("csb_rashcosvki", "Maxim Rashkovsky");
	SetModel("csb_mweather", "Merryweather Merc");
	SetModel("csb_ramp_mex", "Mexican");
	SetModel("cs_michelle", "Michelle");
	SetModel("cs_milton", "Milton McIlroy");
	SetModel("cs_joeminuteman", "Minuteman Joe");
	SetModel("cs_molly", "Molly");
	SetModel("csb_money", "Money Man");
	SetModel("cs_movpremf_01", "Movie Premiere Female");
	SetModel("cs_movpremmale", "Movie Premiere Male");
	SetModel("cs_mrsphillips", "Mrs. Phillips");
	SetModel("csb_mrs_r", "Mrs. Rackman");
	SetModel("cs_mrs_thornhill", "Mrs. Thornhill");
	SetModel("cs_natalia", "Natalia");
	SetModel("cs_nervousron", "Nervous Ron");
	SetModel("cs_nigel", "Nigel");
	SetModel("cs_old_man1a", "Old Man 1");
	SetModel("cs_old_man2", "Old Man 2");
	SetModel("cs_omega", "Omega");
	SetModel("csb_ortega", "Ortega");
	SetModel("csb_oscar", "Oscar");
	SetModel("csb_paige", "Paige Harris");
	SetModel("cs_patricia", "Patricia");
	SetModel("cs_dreyfuss", "Peter Dreyfuss");
	SetModel("csb_porndudes", "Porn Dude");
	SetModel("cs_priest", "Priest");
	SetModel("csb_prologuedriver", "Prologue Driver");
	SetModel("csb_prolsec", "Prologue Security");
	SetModel("cs_prolsec_02", "Prologue Security 2");
	SetModel("csb_reporter", "Reporter");
	SetModel("csb_roccopelosi", "Rocco Pelosi");
	SetModel("cs_russiandrunk", "Russian Drunk");
	SetModel("csb_screen_writer", "Screenwriter");
	SetModel("cs_siemonyetarian", "Simeon Yetarian");
	SetModel("cs_solomon", "Solomon Richards");
	SetModel("cs_stevehains", "Steve Haines");
	SetModel("cs_stretch", "Stretch");
	SetModel("csb_stripper_01", "Stripper");
	SetModel("csb_stripper_02", "Stripper 2");
	SetModel("cs_tanisha", "Tanisha");
	SetModel("cs_taocheng", "Tao Cheng");
	SetModel("cs_taocheng2", "Tao Cheng (Casino)");
	SetModel("cs_taostranslator", "Tao's Translator");
	SetModel("cs_taostranslator2", "Tao's Translator (Casino)");
	SetModel("cs_tenniscoach", "Tennis Coach");
	SetModel("cs_terry", "Terry");
	SetModel("cs_tom", "Tom");
	SetModel("csb_tomcasino", "Tom Connors");
	SetModel("csb_tonya", "Tonya");
	SetModel("csb_thornton", "Thornton Duggan");
	SetModel("cs_tracydisanto", "Tracey De Santa");
	SetModel("csb_trafficwarden", "Traffic Warden");
	SetModel("csb_undercover", "Undercover Cop");
	SetModel("cs_paper", "United Paper Man");
	SetModel("csb_vagspeak", "Vagos Speak");
	SetModel("csb_vincent", "Vincent (Casino)");
	SetModel("cs_wade", "Wade");
	SetModel("cs_chengsr", "Wei Cheng");
	SetModel("cs_zimbor", "Zimbor");
	SetModel("csb_djblamadon", "DJ Black Madonna");
	SetModel("csb_dix", "Dixon");
	SetModel("csb_englishdave", "English Dave");
	SetModel("cs_lazlow_2", "Lazlow 2");
	SetModel("csb_sol", "Soloman");
	SetModel("csb_talcc", "Tale of Us 1");
	SetModel("csb_talmm", "Tale of Us 2");
	SetModel("csb_tonyprince", "Tony Prince");
	SetModel("csb_alan", "Alan Jerome");
	SetModel("csb_bryony", "Bryony");
}
void GangFemale()
{
	Menu::Title("");
	Menu::Subtitle("Player Models");
	SetModel("g_f_y_ballas_01", "Ballas Female");
	SetModel("g_f_y_families_01", "Families Female");
	SetModel("g_f_importexport_01", "Import Export Female");
	SetModel("g_f_y_lost_01", "The Lost MC Female");
	SetModel("g_f_y_vagos_01", "Vagos Female");
}
void GangMale()
{
	Menu::Title("");
	Menu::Subtitle("Player Models");
	SetModel("g_f_importexport_01", "Gang Female (Import-Export)");
	SetModel("g_m_importexport_01", "Gang Male (Import-Export)");
	SetModel("g_m_m_armboss_01", "Armenian Boss");
	SetModel("g_m_m_armgoon_01", "Armenian Goon");
	SetModel("g_m_y_armgoon_02", "Armenian Goon 2");
	SetModel("g_m_m_armlieut_01", "Armenian Lieutenant");
	SetModel("g_m_y_azteca_01", "Azteca");
	SetModel("g_m_y_ballaeast_01", "Ballas East Male");
	SetModel("g_m_y_ballaorig_01", "Ballas Original Male");
	SetModel("g_m_y_ballasout_01", "Ballas South Male");
	SetModel("g_m_m_casrn_01", "Casino Guests?");
	SetModel("g_m_m_chemwork_01", "Chemical Plant Worker");
	SetModel("g_m_m_chiboss_01", "Chinese Boss");
	SetModel("g_m_m_chigoon_01", "Chinese Goon");
	SetModel("g_m_m_chigoon_02", "Chinese Goon 2");
	SetModel("g_m_m_chicold_01", "Chinese Goon Older");
	SetModel("g_m_y_famca_01", "Families CA Male");
	SetModel("g_m_y_famdnf_01", "Families DNF Male");
	SetModel("g_m_y_famfor_01", "Families FOR Male");
	SetModel("g_m_m_korboss_01", "Korean Boss");
	SetModel("g_m_y_korlieut_01", "Korean Lieutenant");
	SetModel("g_m_y_korean_01", "Korean Young Male");
	SetModel("g_m_y_korean_02", "Korean Young Male 2");
	SetModel("g_m_m_mexboss_01", "Mexican Boss");
	SetModel("g_m_m_mexboss_02", "Mexican Boss 2");
	SetModel("g_m_y_mexgang_01", "Mexican Gang Member");
	SetModel("g_m_y_mexgoon_01", "Mexican Goon");
	SetModel("g_m_y_mexgoon_02", "Mexican Goon 2");
	SetModel("g_m_y_mexgoon_03", "Mexican Goon 3");
	SetModel("g_m_y_pologoon_01", "Polynesian Goon");
	SetModel("g_m_y_pologoon_02", "Polynesian Goon 2");
	SetModel("g_m_y_salvaboss_01", "Salvadoran Boss");
	SetModel("g_m_y_salvagoon_01", "Salvadoran Goon");
	SetModel("g_m_y_salvagoon_02", "Salvadoran Goon 2");
	SetModel("g_m_y_salvagoon_03", "Salvadoran Goon 3");
	SetModel("g_m_y_strpunk_01", "Street Punk");
	SetModel("g_m_y_strpunk_02", "Street Punk 2");
	SetModel("g_m_y_lost_01", "The Lost MC Male");
	SetModel("g_m_y_lost_02", "The Lost MC Male 2");
	SetModel("g_m_y_lost_03", "The Lost MC Male 3");
}
void Story()
{
	Menu::Title("");
	Menu::Subtitle("Player Models");
	SetModel("player_zero", "Michael");
	SetModel("player_one", "Franklin");
	SetModel("player_two", "Trevor");
	SetModel("ig_abigail", "Abigail Mathers");
	SetModel("ig_agent", "Agent");
	SetModel("ig_agatha", "Agatha Baker");
	SetModel("ig_avery", "Avery Duggan");
	SetModel("ig_mp_agent14", "Agent 14");
	SetModel("ig_amandatownley", "Amanda De Santa");
	SetModel("ig_andreas", "Andreas Sanchez");
	SetModel("ig_ashley", "Ashley Butler");
	SetModel("ig_avon", "Avon Hertz");
	SetModel("ig_ballasog", "Ballas OG");
	SetModel("ig_benny", "Benny");
	SetModel("ig_bankman", "Bank Manager");
	SetModel("ig_barry", "Barry");
	SetModel("ig_bestmen", "Best Man");
	SetModel("ig_beverly", "Beverly Felton");
	SetModel("ig_brucie2", "Brucie Kibbutz");
	SetModel("ig_orleans", "Bigfoot");
	SetModel("ig_brad", "Brad");
	SetModel("ig_bride", "Bride");
	SetModel("ig_car3guy1", "Car 3 Guy 1");
	SetModel("ig_car3guy2", "Car 3 Guy 2");
	SetModel("ig_casey", "Casey");
	SetModel("ig_chef", "Chef");
	SetModel("ig_chef2", "Chef");
	SetModel("ig_claypain", "Clay Jackson (The Pain Giver)");
	SetModel("ig_clay", "Clay Simons (The Lost)");
	SetModel("ig_cletus", "Cletus");
	SetModel("ig_chrisformage", "Cris Formage");
	SetModel("ig_dale", "Dale");
	SetModel("ig_davenorton", "Dave Norton");
	SetModel("ig_denise", "Denise");
	SetModel("ig_devin", "Devin");
	SetModel("ig_popov", "Dima Popov");
	SetModel("ig_dom", "Dom Beasley");
	SetModel("ig_drfriedlander", "Dr. Friedlander");
	SetModel("ig_tomepsilon", "Epsilon Tom");
	SetModel("ig_fabien", "Fabien");
	SetModel("ig_ramp_gang", "Families Gang Member?");
	SetModel("ig_mrk", "Ferdinand Kerimov (Mr. K)");
	SetModel("ig_fbisuit_01", "FIB Suit");
	SetModel("ig_floyd", "Floyd Hebert");
	SetModel("ig_g", "Gerald");
	SetModel("ig_groom", "Groom");
	SetModel("ig_hao", "Hao");
	SetModel("ig_ramp_hic", "Hick");
	SetModel("ig_ramp_hipster", "Hipster");
	SetModel("ig_hunter", "Hunter");
	SetModel("ig_janet", "Janet");
	SetModel("ig_jay_norris", "Jay Norris");
	SetModel("ig_jewelass", "Jeweller Assistant");
	SetModel("ig_jimmyboston", "Jimmy Boston");
	SetModel("ig_jimmydisanto", "Jimmy De Santa");
	SetModel("ig_johnnyklebitz", "Johnny Klebitz");
	SetModel("ig_josef", "Josef");
	SetModel("ig_josh", "Josh");
	SetModel("ig_karen_daniels", "Karen Daniels");
	SetModel("ig_kerrymcintosh", "Kerry McIntosh");
	SetModel("ig_lamardavis", "Lamar Davis");
	SetModel("ig_lazlow", "Lazlow");
	SetModel("ig_lestercrest", "Lester Crest");
	SetModel("ig_lestercrest_2", "Lester Crest (Doomsday Heist)");
	SetModel("ig_lifeinvad_01", "Life Invader");
	SetModel("ig_lifeinvad_02", "Life Invader 2");
	SetModel("ig_magenta", "Magenta");
	SetModel("ig_manuel", "Manuel");
	SetModel("ig_marnie", "Marnie Allen");
	SetModel("ig_maryann", "Mary-Ann Quinn");
	SetModel("ig_maude", "Maude");
	SetModel("ig_rashcosvki", "Maxim Rashkovsky");
	SetModel("ig_ramp_mex", "Mexican");
	SetModel("ig_michelle", "Michelle");
	SetModel("ig_milton", "Milton McIlroy");
	SetModel("ig_joeminuteman", "Minuteman Joe");
	SetModel("ig_malc", "Malc");
	SetModel("ig_molly", "Molly");
	SetModel("ig_money", "Money Man");
	SetModel("ig_mrsphillips", "Mrs. Phillips");
	SetModel("ig_mrs_thornhill", "Mrs. Thornhill");
	SetModel("ig_natalia", "Natalia");
	SetModel("ig_nervousron", "Nervous Ron");
	SetModel("ig_nigel", "Nigel");
	SetModel("ig_old_man1a", "Old Man 1");
	SetModel("ig_old_man2", "Old Man 2");
	SetModel("ig_omega", "Omega");
	SetModel("ig_oneil", "O'Neil Brothers");
	SetModel("ig_ortega", "Ortega");
	SetModel("ig_paige", "Paige Harris");
	SetModel("ig_patricia", "Patricia");
	SetModel("ig_dreyfuss", "Peter Dreyfuss");
	SetModel("ig_priest", "Priest");
	SetModel("ig_prolsec_02", "Prologue Security 2");
	SetModel("ig_roccopelosi", "Rocco Pelosi");
	SetModel("ig_russiandrunk", "Russian Drunk");
	SetModel("ig_screen_writer", "Screenwriter");
	SetModel("ig_siemonyetarian", "Simeon Yetarian");
	SetModel("ig_solomon", "Solomon Richards");
	SetModel("ig_stevehains", "Steve Haines");
	SetModel("ig_stretch", "Stretch");
	SetModel("ig_talina", "Talina");
	SetModel("ig_tanisha", "Tanisha");
	SetModel("ig_taocheng", "Tao Cheng");
	SetModel("ig_taocheng2", "Tao Cheng (Casino)");
	SetModel("ig_taostranslator", "Tao's Translator");
	SetModel("ig_taostranslator2", "Tao's Translator (Casino)");
	SetModel("ig_tenniscoach", "Tennis Coach");
	SetModel("ig_terry", "Terry");
	SetModel("ig_tonya", "Tonya");
	SetModel("ig_tracydisanto", "Tracey De Santa");
	SetModel("ig_trafficwarden", "Traffic Warden");
	SetModel("ig_tylerdix", "Tyler Dixon");
	SetModel("ig_paper", "United Paper Man");
	SetModel("ig_vagspeak", "Vagos Funeral Speaker");
	SetModel("ig_wade", "Wade");
	SetModel("ig_chengsr", "Wei Cheng");
	SetModel("ig_zimbor", "Zimbor");
	SetModel("ig_djblamadon", "DJ Black Madonna");
	SetModel("ig_djblamryans", "DJ Ryan S");
	SetModel("ig_djblamrupert", "DJ Rupert");
	SetModel("ig_djdixmanager", "DJ Dixon Manager");
	SetModel("ig_djsolfotios", "DJ Fotios");
	SetModel("ig_djsoljakob", "DJ Jakob");
	SetModel("ig_djsolmike", "DJ Mike T");
	SetModel("ig_djsolrobt", "DJ Rob T");
	SetModel("ig_djtalaurelia", " DJ Aurelia");
	SetModel("ig_djtalignazio", "DJ Ignazio");
	SetModel("ig_dix", "Dixon");
	SetModel("ig_englishdave", "English Dave");
	SetModel("ig_djgeneric_01", "Generic DJ");
	SetModel("ig_jimmyboston_02", "Jimmy Boston 2");
	SetModel("ig_kerrymcintosh_02", "Kerry McIntosh 2");
	SetModel("ig_lacey_jones_02", "Lacy Jones 2");
	SetModel("ig_lazlow_2", "Lazlow 2");
	SetModel("ig_sol", "Soloman");
	SetModel("ig_djsolmanager", "Soloman Manager");
	SetModel("ig_talcc", "Tale of Us 1");
	SetModel("ig_talmm", "Tale of Us 2");
	SetModel("ig_tylerdix_02", "Tyler Dixon 2");
	SetModel("ig_tonyprince", "Tony Prince");
	SetModel("ig_sacha", "Sacha Yetarian");
	SetModel("ig_thornton", "Thornton Duggan");
	SetModel("ig_tomcasino", "Tom Connors");
	SetModel("ig_vincent", "Vincent (Casino)");
}
void Multiplayer()
{
	Menu::Title("");
	Menu::Subtitle("Player Models");
	SetModel("mp_s_m_armoured_01", "Armoured Van Security Male");
	SetModel("mp_m_avongoon", "Avon Goon");
	SetModel("mp_f_cocaine_01", "Biker Cocaine Female");
	SetModel("mp_m_cocaine_01", "Biker Cocaine Male");
	SetModel("mp_f_counterfeit_01", "Biker Counterfeit Female");
	SetModel("mp_m_counterfeit_01", "Biker Counterfeit Male");
	SetModel("mp_f_forgery_01", "Biker Forgery Female");
	SetModel("mp_m_forgery_01", "Biker Forgery Male");
	SetModel("mp_f_meth_01", "Biker Meth Female");
	SetModel("mp_m_meth_01", "Biker Meth Male");
	SetModel("mp_f_weed_01", "Biker Weed Female");
	SetModel("mp_m_weed_01", "Biker Weed Male");
	SetModel("mp_f_boatstaff_01", "Boat-Staff Female");
	SetModel("mp_m_boatstaff_01", "Boat-Staff Male");
	SetModel("mp_m_bogdangoon", "Bogdan Goon");
	SetModel("mp_f_chbar_01", "Clubhouse Bar Female");
	SetModel("mp_m_claude_01", "Claude Speed");
	SetModel("mp_f_deadhooker", "Dead Hooker");
	SetModel("mp_m_exarmy_01", "Ex-Army Male");
	SetModel("mp_f_execpa_01", "Executive PA Female");
	SetModel("mp_f_execpa_02", "Executive PA Female 2");
	SetModel("mp_m_execpa_01", "Executive PA Male");
	SetModel("mp_m_famdd_01", "Families DD Male");
	SetModel("mp_m_fibsec_01", "FIB Security");
	SetModel("mp_f_freemode_01", "Freemode Female");
	SetModel("mp_m_freemode_01", "Freemode Male");
	SetModel("mp_f_helistaff_01", "Heli-Staff Female");
	SetModel("mp_m_marston_01", "John Marston");
	SetModel("mp_f_misty_01", "Misty");
	SetModel("mp_m_niko_01", "Niko Bellic");
	SetModel("mp_f_cardesign_01", "Office Garage Mechanic (Female)");
	SetModel("mp_g_m_pros_01", "Pros");
	SetModel("mp_m_securoguard_01", "Securoserve Guard (Male)");
	SetModel("mp_m_shopkeep_01", "Shopkeeper (Male)");
	SetModel("mp_f_stripperlite", "Stripper Lite (Female)");
	SetModel("mp_m_g_vagfun_01", "Vagos Funeral");
	SetModel("mp_m_waremech_01", "Warehouse Mechanic (Male)");
	SetModel("mp_m_weapexp_01", "Weapon Exp (Male)");
	SetModel("mp_m_weapwork_01", "Weapon Work (Male)");
	SetModel("mp_f_bennymech_01", "Benny Mechanic (Female)");
}
void ScenarioFemale()
{
	Menu::Title("");
	Menu::Subtitle("Player Models");
	SetModel("s_f_y_airhostess_01", "Air Hostess");
	SetModel("s_f_m_fembarber", "Barber Female");
	SetModel("s_f_y_bartender_01", "Bartender");
	SetModel("s_f_y_baywatch_01", "Baywatch Female");
	SetModel("s_f_y_casino_01", "Casino Staff");
	SetModel("s_f_y_cop_01", "Cop Female");
	SetModel("s_f_y_factory_01", "Factory Worker Female");
	SetModel("s_f_y_hooker_01", "Hooker");
	SetModel("s_f_y_hooker_02", "Hooker 2");
	SetModel("s_f_y_hooker_03", "Hooker 3");
	SetModel("s_f_y_scrubs_01", "Hospital Scrubs Female");
	SetModel("s_f_m_maid_01", "Maid");
	SetModel("s_f_y_migrant_01", "Migrant Female");
	SetModel("s_f_y_movprem_01", "Movie Premiere Female");
	SetModel("s_f_y_ranger_01", "Ranger Female");
	SetModel("s_f_m_shop_high", "Sales Assistant (High-End)");
	SetModel("s_f_y_shop_low", "Sales Assistant (Low-End)");
	SetModel("s_f_y_shop_mid", "Sales Assistant (Mid-Price)");
	SetModel("s_f_y_sheriff_01", "Sheriff Female");
	SetModel("s_f_y_stripper_01", "Stripper");
	SetModel("s_f_y_stripper_02", "Stripper 2");
	SetModel("s_f_y_stripperlite", "Stripper Lite");
	SetModel("s_f_m_sweatshop_01", "Sweatshop Worker");
	SetModel("s_f_y_sweatshop_01", "Sweatshop Worker Young");
	SetModel("s_f_y_clubbar_01", "Club Bartender Female");
}
void ScenarioMale()
{
	Menu::Title("");
	Menu::Subtitle("Player Models");
	SetModel("s_m_y_airworker", "Air Worker Male");
	SetModel("s_m_m_movalien_01", "Alien");
	SetModel("s_m_y_ammucity_01", "Ammu-Nation City Clerk");
	SetModel("s_m_m_ammucountry", "Ammu-Nation Rural Clerk");
	SetModel("s_m_m_armoured_01", "Armoured Van Security");
	SetModel("s_m_m_armoured_02", "Armoured Van Security 2");
	SetModel("s_m_y_armymech_01", "Army Mechanic");
	SetModel("s_m_y_autopsy_01", "Autopsy Tech");
	SetModel("s_m_m_autoshop_01", "Autoshop Worker");
	SetModel("s_m_m_autoshop_02", "Autoshop Worker 2");
	SetModel("s_m_y_barman_01", "Barman");
	SetModel("s_m_m_cntrybar_01", "Bartender (Rural)");
	SetModel("s_m_y_baywatch_01", "Baywatch Male");
	SetModel("s_m_y_blackops_01", "Black Ops Soldier");
	SetModel("s_m_y_blackops_02", "Black Ops Soldier 2");
	SetModel("s_m_y_blackops_03", "Black Ops Soldier 3");
	SetModel("s_m_m_bouncer_01", "Bouncer");
	SetModel("s_m_y_busboy_01", "Busboy");
	SetModel("s_m_o_busker_01", "Busker");
	SetModel("s_m_y_casino_01", "Casino Staff");
	SetModel("s_m_y_chef_01", "Chef");
	SetModel("s_m_m_chemsec_01", "Chemical Plant Security");
	SetModel("s_m_y_clown_01", "Clown");
	SetModel("s_m_y_construct_01", "construction Worker");
	SetModel("s_m_y_construct_02", "construction Worker 2");
	SetModel("s_m_y_cop_01", "Cop Male");
	SetModel("s_m_m_ccrew_01", "Crew Member");
	SetModel("s_m_y_dealer_01", "Dealer");
	SetModel("s_m_y_devinsec_01", "Devin's Security");
	SetModel("s_m_m_dockwork_01", "Dock Worker");
	SetModel("s_m_y_dockwork_01", "Dock Worker");
	SetModel("s_m_m_doctor_01", "Doctor");
	SetModel("s_m_y_doorman_01", "Doorman");
	SetModel("s_m_y_dwservice_01", "DW Airport Worker");
	SetModel("s_m_y_dwservice_02", "DW Airport Worker 2");
	SetModel("s_m_y_factory_01", "Factory Worker Male");
	SetModel("s_m_m_fiboffice_01", "FIB Office Worker");
	SetModel("s_m_m_fiboffice_02", "FIB Office Worker 2");
	SetModel("s_m_m_fibsec_01", "FIB Security");
	SetModel("s_m_y_fireman_01", "Fireman Male");
	SetModel("s_m_m_gaffer_01", "Gaffer");
	SetModel("s_m_y_garbage", "Garbage Worker");
	SetModel("s_m_m_gardener_01", "Gardener");
	SetModel("s_m_y_grip_01", "Grip");
	SetModel("s_m_m_hairdress_01", "Hairdresser Male");
	SetModel("s_m_m_highsec_01", "High Security");
	SetModel("s_m_m_highsec_02", "High Security 2");
	SetModel("s_m_y_hwaycop_01", "Highway Cop");
	SetModel("s_m_m_ciasec_01", "IAA Security");
	SetModel("s_m_m_janitor", "Janitor");
	SetModel("s_m_m_lathandy_01", "Latino Handyman Male");
	SetModel("s_m_m_lifeinvad_01", "Life Invader Male");
	SetModel("s_m_m_linecook", "Line Cook");
	SetModel("s_m_m_lsmetro_01", "LS Metro Worker Male");
	SetModel("s_m_m_mariachi_01", "Mariachi");
	SetModel("s_m_m_marine_01", "Marine");
	SetModel("s_m_m_marine_02", "Marine 2");
	SetModel("s_m_y_marine_01", "Marine Young");
	SetModel("s_m_y_marine_02", "Marine Young 2");
	SetModel("s_m_y_marine_03", "Marine Young 3");
	SetModel("s_m_y_xmech_01", "Mechanic");
	SetModel("s_m_y_xmech_02", "MC Clubhouse Mechanic");
	SetModel("s_m_m_migrant_01", "Migrant Male");
	SetModel("s_m_y_mime", "Mime Artist");
	SetModel("s_m_m_movspace_01", "Movie Astronaut");
	SetModel("s_m_m_movprem_01", "Movie Premiere Male");
	SetModel("s_m_m_paramedic_01", "Paramedic");
	SetModel("s_m_y_pestcont_01", "Pest Control");
	SetModel("s_m_m_pilot_01", "Pilot");
	SetModel("s_m_y_pilot_01", "Pilot");
	SetModel("s_m_m_pilot_02", "Pilot 2");
	SetModel("s_m_m_postal_01", "Postal Worker Male");
	SetModel("s_m_m_postal_02", "Postal Worker Male 2");
	SetModel("s_m_m_prisguard_01", "Prison Guard");
	SetModel("s_m_y_prisoner_01", "Prisoner");
	SetModel("s_m_y_prismuscl_01", "Prisoner (Muscular)");
	SetModel("s_m_y_ranger_01", "Ranger Male");
	SetModel("s_m_y_robber_01", "Robber");
	SetModel("s_m_y_shop_mask", "Mask Salesman");
	SetModel("s_m_m_scientist_01", "Scientist");
	SetModel("s_m_m_security_01", "Security Guard");
	SetModel("s_m_y_sheriff_01", "Sheriff Male");
	SetModel("s_m_m_snowcop_01", "Snow Cop Male");
	SetModel("s_m_m_strperf_01", "Street Performer");
	SetModel("s_m_m_strpreach_01", "Street Preacher");
	SetModel("s_m_m_strvend_01", "Street Vendor");
	SetModel("s_m_y_strvend_01", "Street Vendor Young");
	SetModel("s_m_y_swat_01", "SWAT");
	SetModel("s_m_m_gentransport", "Transport Worker Male");
	SetModel("s_m_m_trucker_01", "Trucker Male");
	SetModel("s_m_m_ups_01", "UPS Driver");
	SetModel("s_m_m_ups_02", "UPS Driver 2");
	SetModel("s_m_y_uscg_01", "US Coastguard");
	SetModel("s_m_y_valet_01", "Valet");
	SetModel("s_m_y_waiter_01", "Waiter");
	SetModel("s_m_y_westsec_01", "Duggan Secruity");
	SetModel("s_m_y_winclean_01", "Window Cleaner");
	SetModel("s_m_y_clubbar_01", "Club Bartender Male");
	SetModel("s_m_y_waretech_01", "Warehouse Technician");

}
void StoryScenarioFemale()
{
	Menu::Title("");
	Menu::Subtitle("Player Models");
	SetModel("u_f_y_bikerchic", "Biker Chic Female");
	SetModel("u_f_m_corpse_01", "Corpse Female");
	SetModel("u_f_m_casinocash_01", "Casino Cashier");
	SetModel("u_f_m_casinoshop_01", "Casino shop owner");
	SetModel("u_f_m_debbie_01", "Debbie (Agatha´s Secretary)");
	SetModel("u_f_o_carol", "Carol");
	SetModel("u_f_o_eileen", "Eileen");
	SetModel("u_f_y_beth", "Beth");
	SetModel("u_f_y_lauren", "Lauren");
	SetModel("u_f_y_taylor", "Taylor");
	SetModel("u_f_y_corpse_01", "Corpse Young Female");
	SetModel("u_f_y_corpse_02", "Corpse Young Female 2");
	SetModel("u_f_y_hotposh_01", "Hot Posh Female");
	SetModel("u_f_y_comjane", "Jane");
	SetModel("u_f_y_jewelass_01", "Jeweller Assistant");
	SetModel("u_f_m_miranda", "Miranda");
	SetModel("u_f_y_mistress", "Mistress");
	SetModel("u_f_o_moviestar", "Movie Star Female");
	SetModel("u_f_y_poppymich", "Poppy Mitchell");
	SetModel("u_f_y_princess", "Princess");
	SetModel("u_f_o_prolhost_01", "Prologue Host Old Female");
	SetModel("u_f_m_promourn_01", "Prologue Mourner Female");
	SetModel("u_f_y_spyactress", "Spy Actress");
	SetModel("u_f_m_miranda_02", "Miranda 2");
	SetModel("u_f_y_poppymich_02", "Poppy Mitchell 2");
	SetModel("u_f_y_danceburl_01", "Female Club Dancer (Burlesque)");
	SetModel("u_f_y_dancelthr_01", "Female Club Dancer (Leather)");
	SetModel("u_f_y_dancerave_01", "Female Club Dancer (Rave)");
}
void StoryScenarioMale()
{
	Menu::Title("");
	Menu::Subtitle("Player Models");
	SetModel("u_m_y_abner", "Abner");
	SetModel("u_m_m_aldinapoli", "Al Di Napoli Male");
	SetModel("u_m_y_antonb", "Anton Beaudelaire");
	SetModel("u_m_y_juggernaut_01", "Avon Juggernaut");
	SetModel("u_m_y_babyd", "Baby D");
	SetModel("u_m_m_bankman", "Bank Manager Male");
	SetModel("u_m_m_bikehire_01", "Bike Hire Guy");
	SetModel("u_m_m_blane", "Blane");
	SetModel("u_m_m_curtis", "Curtis");
	SetModel("u_m_m_vince", "Vince");
	SetModel("u_m_o_dean", "Dean");
	SetModel("u_m_y_caleb", "Caleb");
	SetModel("u_m_y_croupthief_01", "Casino Thief");
	SetModel("u_m_y_gabriel", "Gabriel");
	SetModel("u_m_y_ushi", "Ushi");
	SetModel("u_m_y_burgerdrug_01", "Burger Drug Worker");
	SetModel("u_m_y_chip", "Chip");
	SetModel("u_m_y_cyclist_01", "Cyclist Male");
	SetModel("u_m_y_corpse_01", "Dead Courier");
	SetModel("u_m_m_doa_01", "DOA Man");
	SetModel("u_m_m_edtoh", "Ed Toh");
	SetModel("u_m_y_militarybum", "Ex-Mil Bum");
	SetModel("u_m_m_fibarchitect", "FIB Architect");
	SetModel("u_m_y_fibmugger_01", "FIB Mugger");
	SetModel("u_m_o_finguru_01", "Financial Guru");
	SetModel("u_m_m_glenstank_01", "Glen-Stank Male");
	SetModel("u_m_m_griff_01", "Griff");
	SetModel("u_m_y_guido_01", "Guido");
	SetModel("u_m_y_gunvend_01", "Gun Vendor");
	SetModel("u_m_y_smugmech_01", "Hangar Mechanic");
	SetModel("u_m_y_hippie_01", "Hippie Male");
	SetModel("u_m_m_streetart_01", "Street Art Male");
	SetModel("u_m_y_imporage", "Impotent Rage");
	SetModel("u_m_o_taphillbilly", "Jesco White (Tapdancing Hillbilly)");
	SetModel("u_m_m_jesus_01", "Jesus");
	SetModel("u_m_m_jewelthief", "Jewel Thief");
	SetModel("u_m_m_jewelsec_01", "Jeweller Security");
	SetModel("u_m_y_justin", "Justin");
	SetModel("u_m_y_baygor", "Kifflom Guy");
	SetModel("u_m_m_willyfist", "Love Fist Willy");
	SetModel("u_m_y_mani", "Mani");
	SetModel("u_m_m_markfost", "Mark Fostenburg");
	SetModel("u_m_m_filmdirector", "Movie Director");
	SetModel("u_m_o_filmnoir", "Movie Corpse (Suited)");
	SetModel("u_m_y_paparazzi", "Paparazzi Young Male");
	SetModel("u_m_m_partytarget", "Party Target");
	SetModel("u_m_y_party_01", "Partygoer");
	SetModel("u_m_y_pogo_01", "Pogo the Monkey");
	SetModel("u_m_y_prisoner_01", "Prisoner");
	SetModel("u_m_y_proldriver_01", "Prologue Driver");
	SetModel("u_m_m_promourn_01", "Prologue Mourner Male");
	SetModel("u_m_m_prolsec_01", "Prologue Security");
	SetModel("u_m_y_rsranger_01", "Republican Space Ranger");
	SetModel("u_m_m_rivalpap", "Rival Paparazzo");
	SetModel("u_m_y_sbike", "Sports Biker");
	SetModel("u_m_m_spyactor", "Spy Actor");
	SetModel("u_m_y_staggrm_01", "Stag Party Groom");
	SetModel("u_m_y_tattoo_01", "Tattoo Artist");
	SetModel("u_m_o_tramp_01", "Tramp Old Male");
	SetModel("u_m_y_zombie_01", "Zombie");
	SetModel("u_m_y_danceburl_01", "Male Club Dancer (Burlesque)");
	SetModel("u_m_y_dancelthr_01", "Male Club Dancer (Leather)");
	SetModel("u_m_y_dancerave_01", "Male Club Dancer (Rave)");
}
void other()
{
	Menu::Title("");
	Menu::Subtitle("Player Models");
	SetModel("hc_driver", "Jewel Heist Driver");
	SetModel("hc_gunman", "Jewel Heist Gunman");
	SetModel("hc_hacker", "Jewel Heist Hacker");
}