#pragma once
#pragma once
void SpawnVeh2(char* toSpawn);
void spawner();
void Superr();
//void Sportss();
//void SportClassicc();
//void Offroadd();
//void Sedanss();
//void Coupess();
//void Muscles();
//void Boatss();
//void Commerciall();
//void Compactss();
//void Cycless();
//void Emergencyy();
//void Helicopterss();
//void Industriall();
//void Militaryy();
//void Planess();
//void Services();
//void Motorcycless();
//void SUVv();
//void Trailerv();
//void Trainsv();
//void Utilityv();
void sportspinSpawner();
void sportclassicsspinSpawner();
void carmenu();
void SUVspinSpawner();
void TrailerspinSpawner();
void TranspinSpawner();
void UtilityspinSpawner();
void BoatspinSpawner();
void CommercialspinSpawner();
void CompactsspinSpawner();
void CoupesspinSpawner();
void CyclesspinSpawner();
void EmergencyspinSpawner();
void HelicoptersspinSpawner();
void IndustrialspinSpawner();
void MilitaryspinSpawner();
void MotorcyclespinSpawner();
void MusclespinSpawner();
void OffRoadspinSpawner();
void PlanesspinSpawner();
void SedansspinSpawner();
void ServicespinSpawner();
void dlccars();

void By_DLC();
//dlc dort by list
void BeachBum();
void Business();
void HighLife();
void ImNotAHipster();
void FlightSchool();
void LastTeamStanding();
void NextGenRelease();
void FestiveSuprise();
void Heists();
void III_Gotten_Gains_part1();
void III_Gotten_Gains_part2();
void halloween();
void Excutives_and_other_Criminals();
void Valentine();
void Bennys_update();
void Finance_and_Felony();


#pragma once
